import { readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

// Guards against documentation drift. Every assertion here corresponds to a real
// inconsistency that shipped once: a stack fact stated two different ways, a link
// to the wrong repo name, install steps for a registry we no longer use.
//
// These are cheap to keep passing and they protect the thing readers judge us on.

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/** Directories that are dependencies, build output, or generated from sources we already scan. */
const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  ".next",
  ".source",
  "dist",
  "out",
  "coverage",
  // Generated by scripts/sync-docs.mjs from ai/*.md, which this suite scans directly.
  "reference",
]);

function walk(dir: string, exts: string[], found: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const abs = join(dir, entry);
    if (statSync(abs).isDirectory()) {
      if (!SKIP_DIRS.has(entry)) walk(abs, exts, found);
    } else if (exts.some((ext) => entry.endsWith(ext))) {
      found.push(abs);
    }
  }
  return found;
}

function read(file: string): string {
  return readFileSync(resolve(repoRoot, file), "utf8");
}

/** Every prose file we author, as [repo-relative path, contents]. */
function docs(): Array<[string, string]> {
  return walk(repoRoot, [".md", ".mdx"]).map((abs) => [
    relative(repoRoot, abs).replace(/\\/g, "/"),
    readFileSync(abs, "utf8"),
  ]);
}

/** Report every offending file at once rather than failing on the first. */
function filesMatching(pattern: RegExp): string[] {
  return docs()
    .filter(([, body]) => pattern.test(body))
    .map(([path]) => path);
}

describe("stack facts are stated once and consistently", () => {
  it("names Lucide as the icon library, never Tabler", () => {
    // ARCHITECTURE.md is the source of truth and all ~100 real imports are lucide-react.
    expect(filesMatching(/\bTabler\b/)).toEqual([]);
  });

  it("declares the icon library in ai/ARCHITECTURE.md", () => {
    expect(read("ai/ARCHITECTURE.md")).toMatch(/Lucide/);
  });
});

describe("links point at resources that exist", () => {
  it("uses the full Platform-Foundations repo name", () => {
    // The repo is PlainConceptsPlatform/Platform-Foundations; the short form 404s.
    expect(filesMatching(/PlainConceptsPlatform\/Foundations\b/)).toEqual([]);
  });

  it("does not reference the pre-rename CKGrafico org for Platform tools", () => {
    expect(filesMatching(/CKGrafico\/(loop-task|opencode-onboard)/)).toEqual([]);
  });
});

describe("install instructions match how the packages actually ship", () => {
  it("does not ask readers to configure a private registry or token", () => {
    // Both packages publish publicly to registry.npmjs.org; see their publishConfig.
    const stale = /npm\.pkg\.github\.com|NPM_REGISTRY_TOKEN|read:packages/;
    expect(filesMatching(stale)).toEqual([]);
  });

  it("keeps both packages configured for public npm", () => {
    for (const pkg of ["packages/theme", "packages/ui-components"]) {
      const manifest = JSON.parse(read(`${pkg}/package.json`));
      expect(manifest.publishConfig).toMatchObject({
        registry: "https://registry.npmjs.org",
        access: "public",
      });
    }
  });
});

describe("navigation reaches every page", () => {
  it("lists the generated reference group in the docs sidebar", () => {
    const meta = JSON.parse(read("apps/docs/content/docs/meta.json"));
    expect(meta.pages).toContain("reference");
  });

  it("lists every top-level content page or group in the sidebar", () => {
    const contentDir = resolve(repoRoot, "apps/docs/content/docs");
    const meta = JSON.parse(read("apps/docs/content/docs/meta.json"));
    const listed = new Set<string>(meta.pages);

    const onDisk = readdirSync(contentDir)
      .filter((entry) => !SKIP_DIRS.has(entry) && entry !== "meta.json")
      .map((entry) => entry.replace(/\.mdx?$/, ""));

    expect(onDisk.filter((slug) => !listed.has(slug))).toEqual([]);
  });
});

describe("the public repo does not leak infrastructure identifiers", () => {
  it("keeps Azure subscription and tenant ids out of workflows", () => {
    const workflows = walk(resolve(repoRoot, ".github/workflows"), [".yml", ".yaml"]);
    const guid = /\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/i;

    const leaking = workflows
      .filter((abs) => guid.test(readFileSync(abs, "utf8")))
      .map((abs) => relative(repoRoot, abs).replace(/\\/g, "/"));

    expect(leaking).toEqual([]);
  });
});
