import { readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

// Guards against documentation drift. Every assertion here corresponds to a real
// inconsistency that shipped once: a stack fact stated two different ways, a link
// to the wrong repo name, install steps for a registry we no longer use.
//
// These are cheap to keep passing and they protect the thing readers judge us on.

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/** Directories that are dependencies, build output, or generated from sources we already scan. */
const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  ".next",
  ".source",
  "dist",
  "out",
  "coverage",
  // Generated by scripts/sync-docs.mjs from ai/*.md, which this suite scans directly.
  "reference",
]);

function walk(dir: string, exts: string[], found: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const abs = join(dir, entry);
    if (statSync(abs).isDirectory()) {
      if (!SKIP_DIRS.has(entry)) walk(abs, exts, found);
    } else if (exts.some((ext) => entry.endsWith(ext))) {
      found.push(abs);
    }
  }
  return found;
}

function read(file: string): string {
  return readFileSync(resolve(repoRoot, file), "utf8");
}

/** Every prose file we author, as [repo-relative path, contents]. */
function docs(): Array<[string, string]> {
  return walk(repoRoot, [".md", ".mdx"]).map((abs) => [
    relative(repoRoot, abs).replace(/\\/g, "/"),
    readFileSync(abs, "utf8"),
  ]);
}

/** Report every offending file at once rather than failing on the first. */
function filesMatching(pattern: RegExp): string[] {
  return docs()
    .filter(([, body]) => pattern.test(body))
    .map(([path]) => path);
}

describe("stack facts are stated once and consistently", () => {
  it("names Lucide as the icon library, never Tabler", () => {
    // ARCHITECTURE.md is the source of truth and all ~100 real imports are lucide-react.
    expect(filesMatching(/\bTabler\b/)).toEqual([]);
  });

  it("declares the icon library in ai/ARCHITECTURE.md", () => {
    expect(read("ai/ARCHITECTURE.md")).toMatch(/Lucide/);
  });
});

describe("links point at resources that exist", () => {
  it("uses the repo name the remote actually serves", () => {
    // Ground truth is `git remote -v`: https://github.com/PlainConceptsPlatform/Foundations.
    // "Platform-Foundations" is a stale earlier name and every such URL 404s. The
    // display name of the project is still "Platform Foundations" (with a space),
    // so only match it as part of a github.com URL or a package repository field.
    expect(filesMatching(/github\.com\/PlainConceptsPlatform\/Platform-Foundations/)).toEqual([]);
  });

  it("points both published packages at the real repository", () => {
    for (const pkg of ["packages/theme", "packages/ui-components"]) {
      const manifest = JSON.parse(read(`${pkg}/package.json`));
      expect(manifest.repository.url).toBe(
        "git+https://github.com/PlainConceptsPlatform/Foundations.git",
      );
    }
  });

  it("does not reference the pre-rename CKGrafico org for Platform tools", () => {
    expect(filesMatching(/CKGrafico\/(loop-task|opencode-onboard)/)).toEqual([]);
  });
});

describe("install instructions match how the packages actually ship", () => {
  it("does not ask readers to configure a private registry or token", () => {
    // Both packages publish publicly to registry.npmjs.org; see their publishConfig.
    const stale = /npm\.pkg\.github\.com|NPM_REGISTRY_TOKEN|read:packages/;
    expect(filesMatching(stale)).toEqual([]);
  });

  it("installs the Platform tools by their scoped npm names", () => {
    // The unscoped `loop-task` and `opencode-onboard` are earlier releases of the
    // same tools that no longer track the scoped ones (loop-task was 2.6.0 unscoped
    // versus 2.9.1 scoped), so telling a reader to install them hands them a stale
    // version. The binaries are still named without the scope; only install and npx
    // invocations need it.
    const unscoped =
      /(?:npm (?:install|i)(?:\s+-g)?|pnpm add(?:\s+-g)?|yarn (?:global )?add|npx)\s+(?:loop-task|opencode-onboard)(?![\w/-])/;

    expect(filesMatching(unscoped)).toEqual([]);
  });

  it("keeps both packages configured for public npm", () => {
    for (const pkg of ["packages/theme", "packages/ui-components"]) {
      const manifest = JSON.parse(read(`${pkg}/package.json`));
      expect(manifest.publishConfig).toMatchObject({
        registry: "https://registry.npmjs.org",
        access: "public",
      });
    }
  });
});

describe("navigation reaches every page", () => {
  it("lists the generated reference group in the docs sidebar", () => {
    // Spread as "...reference" rather than listed as "reference": the folder's own
    // meta title is also "Reference", so listing it under a ---Reference--- separator
    // rendered the heading twice.
    const meta = JSON.parse(read("apps/docs/content/docs/meta.json"));
    expect(meta.pages).toContain("...reference");
  });

  it("lists every top-level content page or group in the sidebar", () => {
    const contentDir = resolve(repoRoot, "apps/docs/content/docs");
    const meta = JSON.parse(read("apps/docs/content/docs/meta.json"));

    // A folder can be listed by name ("frontend") or spread ("...reference", which
    // inlines its pages under the preceding separator). Both count as reachable.
    const listed = new Set<string>(
      (meta.pages as string[]).map((entry) => entry.replace(/^\.\.\./, "")),
    );

    const onDisk = readdirSync(contentDir)
      .filter((entry) => !SKIP_DIRS.has(entry) && entry !== "meta.json")
      .map((entry) => entry.replace(/\.mdx?$/, ""));

    expect(onDisk.filter((slug) => !listed.has(slug))).toEqual([]);
  });

  it("does not duplicate sidebar entries in the navbar", () => {
    // The navbar `links` array used to repeat four sidebar entries. On a narrow
    // viewport Fumadocs folds the navbar into the sidebar, so each appeared twice.
    const config = read("apps/docs/app/layout.config.tsx");
    expect(config).not.toMatch(/^\s*links:\s*\[/m);
  });
});

describe("the docs site is themed by the package it documents", () => {
  it("maps the Fumadocs chrome onto the Platform tokens", () => {
    // Without these, the navbar/sidebar/TOC render in stock Fumadocs neutral and
    // the site never shows the brand blue it exists to document.
    const css = read("apps/docs/app/global.css");

    for (const token of [
      "--color-fd-background",
      "--color-fd-foreground",
      "--color-fd-primary",
      "--color-fd-accent",
      "--color-fd-muted",
      "--color-fd-border",
      "--color-fd-ring",
    ]) {
      // Match the declaration, not the bare name: "--color-fd-primary" is a
      // prefix of "--color-fd-primary-foreground" and would pass either way.
      expect(css, `${token} must be aliased to a Platform token`).toContain(`${token}:`);
    }
  });

  it("loads the Radix overlay animations", () => {
    // tw-animate-css supplies animate-in/fade-in/zoom-in. It was a declared
    // dependency that nothing imported, so every overlay opened with no motion.
    expect(read("apps/docs/app/global.css")).toMatch(/@import\s+"tw-animate-css"/);
  });

  it("defines the token groups the shadcn Sidebar and charts consume, in both modes", () => {
    const theme = read("packages/theme/src/theme.css");

    for (const token of [
      "--sidebar",
      "--sidebar-foreground",
      "--sidebar-accent",
      "--sidebar-accent-foreground",
      "--sidebar-border",
      "--sidebar-ring",
      "--chart-1",
      "--chart-5",
    ]) {
      // Declared twice: once under :root and once under .dark. A token present in
      // only one mode renders the component unstyled in the other.
      const declarations = theme.split(`${token}:`).length - 1;
      expect(
        declarations,
        `${token} should be declared for light and dark, found ${declarations}`,
      ).toBeGreaterThanOrEqual(2);
    }
  });

  it("neutralizes every shadow scale, so vendored shadcn shadows paint nothing", () => {
    const theme = read("packages/theme/src/theme.css");

    // 29 vendored components ship shadow-* classes. Rather than patch them all and
    // fight `shadcn add`, the scale they resolve from is overridden.
    const scales = [
      ["--shadow", ["2xs", "xs", "sm", "md", "lg", "xl", "2xl"]],
      ["--inset-shadow", ["2xs", "xs", "sm"]],
      ["--drop-shadow", ["xs", "sm", "md", "lg", "xl", "2xl"]],
      ["--text-shadow", ["2xs", "xs", "sm", "md", "lg"]],
    ] as const;

    for (const [prefix, steps] of scales) {
      for (const step of steps) {
        expect(theme, `${prefix}-${step} must be neutralized`).toContain(
          `${prefix}-${step}: 0 0 #0000;`,
        );
      }
    }
  });

  it("never neutralizes a shadow with `none`, which would break focus rings", () => {
    // Tailwind composes ring and inset-ring into the same box-shadow declaration.
    // `none` inside a comma-separated list is invalid CSS, so the browser drops the
    // whole declaration and the focus ring disappears with it.
    const theme = read("packages/theme/src/theme.css");
    const offenders = [...theme.matchAll(/--(?:inset-|drop-|text-)?shadow-[0-9a-z]+:\s*([^;]+);/g)]
      .map((match) => match[1]?.trim())
      .filter((value) => value !== "0 0 #0000");

    expect(
      offenders,
      `shadow scale values must be "0 0 #0000", found: ${offenders.join(", ")}`,
    ).toHaveLength(0);
  });

  it("exposes those groups as Tailwind utilities", () => {
    // bg-sidebar / text-chart-1 only exist if declared inside @theme inline.
    const theme = read("packages/theme/src/theme.css");
    expect(theme).toContain("--color-sidebar:");
    expect(theme).toContain("--color-chart-1:");
  });
});

describe("the public repo does not leak infrastructure identifiers", () => {
  it("keeps Azure subscription and tenant ids out of workflows", () => {
    const workflows = walk(resolve(repoRoot, ".github/workflows"), [".yml", ".yaml"]);
    const guid = /\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/i;

    const leaking = workflows
      .filter((abs) => guid.test(readFileSync(abs, "utf8")))
      .map((abs) => relative(repoRoot, abs).replace(/\\/g, "/"));

    expect(leaking).toEqual([]);
  });
});

describe("the workflow examples stay runnable", () => {
  const examples = ["workflows/refine.md", "workflows/implement.md"];

  // A wrong value here is not an error: the trigger silently never fires. gh-aw
  // title-cases the filename into a name when this is absent, so referencing the
  // filename from another workflow's `workflow_run` would resolve to nothing.
  it("sets an explicit workflow name", () => {
    for (const file of examples) {
      expect(read(file), file).toMatch(/^name: "Agent: /m);
    }
  });

  // Both are needed. Without runs-on-slim the framework jobs run somewhere else than
  // the agent, which defeats the point of choosing a runner at all.
  it("pins both runner keys", () => {
    for (const file of examples) {
      const body = read(file);
      expect(body, file).toMatch(/^runs-on: /m);
      expect(body, file).toMatch(/^runs-on-slim: /m);
    }
  });

  // permissions, engine, model and runs-on do not merge from an import, so each
  // example has to carry them even though the shared fragments exist.
  it("keeps the unmergeable fields local and imports the rest", () => {
    for (const file of examples) {
      const body = read(file);
      expect(body, file).toMatch(/^permissions: read-all$/m);
      expect(body, file).toContain("shared/platform-defaults.md");
      expect(body, file).toContain("shared/opencode-ci.md");
    }
  });

  // The provider chain: `openai` satisfies gh-aw's fixed allowlist, `plainconcepts`
  // is what opencode.ci.json declares against gh-aw's proxy. Changing one without the
  // other routes the run at a provider that does not exist.
  it("keeps the model aliasing consistent across the chain", () => {
    const provider = JSON.parse(read("workflows/opencode.ci.json"));
    expect(Object.keys(provider.provider)).toContain("plainconcepts");
    expect(provider.model).toBe("plainconcepts/glm-5-2");

    for (const file of examples) {
      const body = read(file);
      expect(body, file).toMatch(/^model: openai\//m);
      expect(body, file).toContain("plainconcepts/glm-5-2");
    }
  });

  // Every write goes through safe outputs, and the diagram is what a human reads first.
  it("declares safe outputs and ships a diagram", () => {
    for (const file of examples) {
      const body = read(file);
      expect(body, file).toContain("safe-outputs:");
      expect(body, file).toContain("```mermaid");
      // The shared Platform classDef set, so diagrams read the same everywhere.
      expect(body, file).toContain("classDef decision fill:#fff8e8");
    }
  });

  // The docs quote these files. If an example drops a label the prose still claims,
  // the reader copies a workflow that cannot do what the page says it does.
  it("uses the label set the docs document", () => {
    const refine = read("workflows/refine.md");
    expect(refine).toContain("allowed: [refined]");
    expect(refine).toContain("allowed: [refine]");

    const implement = read("workflows/implement.md");
    expect(implement).toContain("allowed: [bot-working, review]");
    expect(implement).toContain("allowed: [implement, bot-working]");
  });
});
